// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdnpbjmwyfgsjqwimmfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbnBiam13eWZnc2pxd2ltbWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTMyMjEsImV4cCI6MjA2MzkyOTIyMX0.kE3eq7LkbxBAD__LUMueD2bTnzm5cMQacxsXGdJGDR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);